---

- include_vars: vars.yaml

- name: Setup mysql configuration file
  template:
          src: my.cnf.j2
          dest: /etc/mysql/my.cnf
  notify:
          - Restart mysql service 

- name: Setup /root/.my.cnf
  template:
          src: rootmycnf.j2
          dest: /root/.my.cnf
          mode: 0600
          owner: root

- name: Change root mysql login password
  command: mysql -u root -e "alter user 'root'@'localhost' identified with mysql_native_password by '{{ mysql_root_pass }}'"
  ignore_errors: yes

- name: Create Drupal database
  mysql_db:
          login_user: root
          name: "{{ drupal_db_name }}"
          state: present
  become: yes

- name: Create Drupal user
  mysql_user:
          name: "{{ drupal_db_user }}"
          password: seco0re
          priv: '"{{ drupal_db_name }}".*:ALL'
