---

- name: Restart mysql service
  systemd:
          name: mysql
          state: restarted
  become: yes

- name: Restart nginx service
  systemd:
          name: nginx
          state: restarted
  become: yes
